// <auto-generated />
using System;
using KSol.RDPGateway.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KSol.RDPGateway.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260628204219_RemoveRdpOptions")]
    partial class RemoveRdpOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KSol.RDPGateway.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NtHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KSol.RDPGateway.Models.ProxmoxBackend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiTokenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiTokenSecret")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultRdpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdleTimeoutHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KdcHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("KerberosRealm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PauseAction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VerifyTls")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProxmoxBackends");
                });

            modelBuilder.Entity("KSol.RDPGateway.Models.RDPResource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpmiHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpmiUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastActivityUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("OsType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtectedIpmiPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedSshKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProxmoxBackendId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProxmoxNode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProxmoxVmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShutdownCommand")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SshUser")
                        .HasColumnType("TEXT");

                    b.Property<int>("WakeMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WolMacAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProxmoxBackendId");

                    b.ToTable("RDPResources");
                });

            modelBuilder.Entity("KSol.RDPGateway.Models.RDPResourceUserAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("RDPResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RDPResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("RDPResourceUserAuthorizations");
                });

            modelBuilder.Entity("KSol.RDPGateway.Models.Recording", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesktopFilePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MicFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("RDPResourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RDPResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("KSol.RDPGateway.Models.RecordingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RDPResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecordingRules");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KSol.RDPGateway.Models.RDPResource", b =>
                {
                    b.HasOne("KSol.RDPGateway.Models.ProxmoxBackend", "ProxmoxBackend")
                        .WithMany()
                        .HasForeignKey("ProxmoxBackendId");

                    b.OwnsOne("KSol.RDPGateway.Models.ConnectionDefaults", "DefaultConnectionDefaults", b1 =>
                        {
                            b1.Property<string>("RDPResourceId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Audio")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Camera")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Clipboard")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("GfxMode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Microphone")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PerformanceFlags")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RDPResourceId");

                            b1.ToTable("RDPResources");

                            b1.ToJson("DefaultConnectionDefaults");

                            b1.WithOwner()
                                .HasForeignKey("RDPResourceId");
                        });

                    b.Navigation("DefaultConnectionDefaults");

                    b.Navigation("ProxmoxBackend");
                });

            modelBuilder.Entity("KSol.RDPGateway.Models.RDPResourceUserAuthorization", b =>
                {
                    b.HasOne("KSol.RDPGateway.Models.RDPResource", "RDPResource")
                        .WithMany()
                        .HasForeignKey("RDPResourceId");

                    b.HasOne("KSol.RDPGateway.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsOne("KSol.RDPGateway.Models.ConnectionDefaults", "ConnectionDefaults", b1 =>
                        {
                            b1.Property<string>("RDPResourceUserAuthorizationId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Audio")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Camera")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Clipboard")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("GfxMode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Microphone")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PerformanceFlags")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RDPResourceUserAuthorizationId");

                            b1.ToTable("RDPResourceUserAuthorizations");

                            b1.ToJson("ConnectionDefaults");

                            b1.WithOwner()
                                .HasForeignKey("RDPResourceUserAuthorizationId");
                        });

                    b.Navigation("ConnectionDefaults");

                    b.Navigation("RDPResource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KSol.RDPGateway.Models.Recording", b =>
                {
                    b.HasOne("KSol.RDPGateway.Models.RDPResource", "RDPResource")
                        .WithMany()
                        .HasForeignKey("RDPResourceId");

                    b.HasOne("KSol.RDPGateway.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("RDPResource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KSol.RDPGateway.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KSol.RDPGateway.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KSol.RDPGateway.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KSol.RDPGateway.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
