// <auto-generated />
using System;
using KSol.ZeroVDI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KSol.ZeroVDI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629212719_AddVdiGenerateCredentials")]
    partial class AddVdiGenerateCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KSol.ZeroVDI.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmailTwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NtHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("Category");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.DevicePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Audio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Camera")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Clipboard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Microphone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DevicePolicies");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.ProxmoxBackend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiTokenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiTokenSecret")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultRdpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdleTimeoutHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KdcHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("KerberosRealm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PauseAction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VerifyTls")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProxmoxBackends");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.RDPResource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpmiHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpmiUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastActivityUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("OsType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtectedIpmiPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedSshKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedWindowsPassword")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProxmoxBackendId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProxmoxNode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProxmoxVmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShutdownCommand")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShutdownMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SshUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("VdiInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("WakeMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WindowsUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("WolMacAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProxmoxBackendId");

                    b.ToTable("RDPResources");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.RDPResourceGroupAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RDPResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RDPResourceId");

                    b.HasIndex("GroupId", "RDPResourceId")
                        .IsUnique();

                    b.ToTable("RDPResourceGroupAuthorizations");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.RDPResourceUserAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("RDPResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RDPResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("RDPResourceUserAuthorizations");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.Recording", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioSha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraSha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChainHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesktopFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesktopSha256")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Encrypted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MicFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("MicSha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("RDPResourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RDPResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.RecordingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RDPResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecordingRules");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.UserGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.UserGroupMembership", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("UserGroupMemberships");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.VdiInstance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLeasedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProxmoxNode")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProxmoxVmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RDPResourceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("RDPResourceId");

                    b.HasIndex("PoolId", "OwnerUserId")
                        .IsUnique()
                        .HasFilter("\"OwnerUserId\" IS NOT NULL");

                    b.ToTable("VdiInstances");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.VdiPool", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CiSshKeys")
                        .HasColumnType("TEXT");

                    b.Property<string>("CiUser")
                        .HasColumnType("TEXT");

                    b.Property<int>("CloneMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainJoinUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainOu")
                        .HasColumnType("TEXT");

                    b.Property<int>("FloatingReset")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GenerateCredentials")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostnamePattern")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdentityMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OsType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtectedCiPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedDomainJoinPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProxmoxBackendId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetNode")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetStorage")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateVmId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VmidRangeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VmidRangeStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProxmoxBackendId");

                    b.ToTable("VdiPools");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.VdiPoolAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.HasIndex("PoolId", "GroupId")
                        .IsUnique();

                    b.HasIndex("PoolId", "UserId")
                        .IsUnique();

                    b.ToTable("VdiPoolAssignments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.RDPResource", b =>
                {
                    b.HasOne("KSol.ZeroVDI.Models.ProxmoxBackend", "ProxmoxBackend")
                        .WithMany()
                        .HasForeignKey("ProxmoxBackendId");

                    b.OwnsOne("KSol.ZeroVDI.Models.ConnectionDefaults", "DefaultConnectionDefaults", b1 =>
                        {
                            b1.Property<string>("RDPResourceId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Audio")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Camera")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Clipboard")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("GfxMode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Microphone")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PerformanceFlags")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RDPResourceId");

                            b1.ToTable("RDPResources");

                            b1.ToJson("DefaultConnectionDefaults");

                            b1.WithOwner()
                                .HasForeignKey("RDPResourceId");
                        });

                    b.Navigation("DefaultConnectionDefaults");

                    b.Navigation("ProxmoxBackend");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.RDPResourceGroupAuthorization", b =>
                {
                    b.HasOne("KSol.ZeroVDI.Models.UserGroup", "Group")
                        .WithMany("ResourceAuthorizations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KSol.ZeroVDI.Models.RDPResource", "RDPResource")
                        .WithMany()
                        .HasForeignKey("RDPResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("RDPResource");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.RDPResourceUserAuthorization", b =>
                {
                    b.HasOne("KSol.ZeroVDI.Models.RDPResource", "RDPResource")
                        .WithMany()
                        .HasForeignKey("RDPResourceId");

                    b.HasOne("KSol.ZeroVDI.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsOne("KSol.ZeroVDI.Models.ConnectionDefaults", "ConnectionDefaults", b1 =>
                        {
                            b1.Property<string>("RDPResourceUserAuthorizationId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Audio")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Camera")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Clipboard")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("GfxMode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Microphone")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PerformanceFlags")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RDPResourceUserAuthorizationId");

                            b1.ToTable("RDPResourceUserAuthorizations");

                            b1.ToJson("ConnectionDefaults");

                            b1.WithOwner()
                                .HasForeignKey("RDPResourceUserAuthorizationId");
                        });

                    b.Navigation("ConnectionDefaults");

                    b.Navigation("RDPResource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.Recording", b =>
                {
                    b.HasOne("KSol.ZeroVDI.Models.RDPResource", "RDPResource")
                        .WithMany()
                        .HasForeignKey("RDPResourceId");

                    b.HasOne("KSol.ZeroVDI.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("RDPResource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.UserGroupMembership", b =>
                {
                    b.HasOne("KSol.ZeroVDI.Models.UserGroup", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KSol.ZeroVDI.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.VdiInstance", b =>
                {
                    b.HasOne("KSol.ZeroVDI.Models.ApplicationUser", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KSol.ZeroVDI.Models.VdiPool", "Pool")
                        .WithMany("Instances")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KSol.ZeroVDI.Models.RDPResource", "RDPResource")
                        .WithMany()
                        .HasForeignKey("RDPResourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerUser");

                    b.Navigation("Pool");

                    b.Navigation("RDPResource");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.VdiPool", b =>
                {
                    b.HasOne("KSol.ZeroVDI.Models.ProxmoxBackend", "ProxmoxBackend")
                        .WithMany()
                        .HasForeignKey("ProxmoxBackendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("KSol.ZeroVDI.Models.ConnectionDefaults", "ConnectionDefaults", b1 =>
                        {
                            b1.Property<string>("VdiPoolId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Audio")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Camera")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Clipboard")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("GfxMode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Microphone")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PerformanceFlags")
                                .HasColumnType("INTEGER");

                            b1.HasKey("VdiPoolId");

                            b1.ToTable("VdiPools");

                            b1.ToJson("ConnectionDefaults");

                            b1.WithOwner()
                                .HasForeignKey("VdiPoolId");
                        });

                    b.Navigation("ConnectionDefaults");

                    b.Navigation("ProxmoxBackend");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.VdiPoolAssignment", b =>
                {
                    b.HasOne("KSol.ZeroVDI.Models.UserGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KSol.ZeroVDI.Models.VdiPool", "Pool")
                        .WithMany("Assignments")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KSol.ZeroVDI.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Group");

                    b.Navigation("Pool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KSol.ZeroVDI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KSol.ZeroVDI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KSol.ZeroVDI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KSol.ZeroVDI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.UserGroup", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("ResourceAuthorizations");
                });

            modelBuilder.Entity("KSol.ZeroVDI.Models.VdiPool", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Instances");
                });
#pragma warning restore 612, 618
        }
    }
}
